# Generated by Django 3.2.6 on 2021-08-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameCompany', models.CharField(max_length=500)),
                ('ID_gruppa', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
    ]
