# Generated by Django 3.2.6 on 2021-08-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_telegram', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=14)),
                ('url_bitrix', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
    ]
